services:
  postgres:
    image: postgres:15-alpine
    container_name: services-api-postgres
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong_services
    ports:
      - '5433:5432'
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kong -d kong_services']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
